import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Parse command line args to check if we're silently running (e.g. from hooks)
const isSilent = process.argv.includes('--silent');

// Read DATABASE_PROVIDER from process.env (injected by with-env.ts or directly available)
const provider =
  process.env.DATABASE_PROVIDER || process.env.VITE_DATABASE_PROVIDER;

let exportFile = './schema.postgres';
if (provider === 'none') {
  exportFile = './schema.postgres';
} else if (provider === 'sqlite' || provider === 'turso') {
  exportFile = './schema.sqlite';
} else if (provider === 'mysql') {
  exportFile = './schema.mysql';
} else if (provider === 'postgresql' || provider === 'postgres') {
  exportFile = './schema.postgres';
} else {
  exportFile = './schema.postgres'; // Default
  if (!isSilent) {
    console.warn(
      `⚠️  No valid DATABASE_PROVIDER found in env (got '${provider}'). Defaulting to postgresql.`
    );
  }
}

// Get project root path properly for ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '../..');
const schemaPath = path.resolve(projectRoot, 'src/config/db/schema.ts');

const content = `// Auto-generated file. Do not edit directly.
// This file is generated by scripts/db/sync-schema.ts based on DATABASE_PROVIDER in .env
export * from '${exportFile}';
`;

try {
  fs.writeFileSync(schemaPath, content, 'utf-8');
  if (!isSilent) {
    console.log(
      `✅ Synced schema.ts to export ${exportFile} (Provider: ${provider || 'none'})`
    );
  }
} catch (error) {
  console.error(`❌ Failed to sync schema.ts:`, error);
  process.exit(1);
}
