/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123indexnowKeyChar125DottxtRouteImport } from './routes/{$indexnowKey}[.]txt'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125ConfigRouteImport } from './routes/{-$locale}/config'
import { Route as Char123LocaleChar125DocsRouteImport } from './routes/{-$locale}/_docs'
import { Route as Char123LocaleChar125ShiponceRouteRouteImport } from './routes/{-$locale}/shiponce/route'
import { Route as Char123LocaleChar125OauthRouteRouteImport } from './routes/{-$locale}/_oauth/route'
import { Route as Char123LocaleChar125LandingRouteRouteImport } from './routes/{-$locale}/_landing/route'
import { Route as Char123LocaleChar125AuthRouteRouteImport } from './routes/{-$locale}/_auth/route'
import { Route as Char123LocaleChar125ShiponceIndexRouteImport } from './routes/{-$locale}/shiponce/index'
import { Route as Char123LocaleChar125LandingIndexRouteImport } from './routes/{-$locale}/_landing/index'
import { Route as Char123LocaleChar125ShiponceSubscriptionsRouteImport } from './routes/{-$locale}/shiponce/subscriptions'
import { Route as Char123LocaleChar125ShiponcePermissionsRouteImport } from './routes/{-$locale}/shiponce/permissions'
import { Route as Char123LocaleChar125ShiponcePaymentsRouteImport } from './routes/{-$locale}/shiponce/payments'
import { Route as Char123LocaleChar125ShiponceNoPermissionRouteImport } from './routes/{-$locale}/shiponce/no-permission'
import { Route as Char123LocaleChar125ShiponceCreditsRouteImport } from './routes/{-$locale}/shiponce/credits'
import { Route as Char123LocaleChar125ShiponceAiTasksRouteImport } from './routes/{-$locale}/shiponce/ai-tasks'
import { Route as Char123LocaleChar125OauthAuthPopupRouteImport } from './routes/{-$locale}/_oauth/auth-popup'
import { Route as Char123LocaleChar125OauthAuthCallbackRouteImport } from './routes/{-$locale}/_oauth/auth-callback'
import { Route as Char123LocaleChar125LandingVideoGeneratorRouteImport } from './routes/{-$locale}/_landing/video-generator'
import { Route as Char123LocaleChar125LandingUpdatesRouteImport } from './routes/{-$locale}/_landing/updates'
import { Route as Char123LocaleChar125LandingTermsOfServiceRouteImport } from './routes/{-$locale}/_landing/terms-of-service'
import { Route as Char123LocaleChar125LandingShowcasesRouteImport } from './routes/{-$locale}/_landing/showcases'
import { Route as Char123LocaleChar125LandingShowcaseRouteImport } from './routes/{-$locale}/_landing/showcase'
import { Route as Char123LocaleChar125LandingPrivacyPolicyRouteImport } from './routes/{-$locale}/_landing/privacy-policy'
import { Route as Char123LocaleChar125LandingPricingRouteImport } from './routes/{-$locale}/_landing/pricing'
import { Route as Char123LocaleChar125LandingImageGeneratorRouteImport } from './routes/{-$locale}/_landing/image-generator'
import { Route as Char123LocaleChar125LandingGenerateRouteImport } from './routes/{-$locale}/_landing/generate'
import { Route as Char123LocaleChar125LandingFeedbackRouteImport } from './routes/{-$locale}/_landing/feedback'
import { Route as Char123LocaleChar125LandingExamplesRouteImport } from './routes/{-$locale}/_landing/examples'
import { Route as Char123LocaleChar125LandingSplatRouteImport } from './routes/{-$locale}/_landing/$'
import { Route as Char123LocaleChar125AuthNoPermissionRouteImport } from './routes/{-$locale}/_auth/no-permission'
import { Route as ApiProxyFileRouteImport } from './routes/api/proxy/file'
import { Route as ApiPaymentCallbackRouteImport } from './routes/api/payment/callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as Char123LocaleChar125LandingSettingsRouteRouteImport } from './routes/{-$locale}/_landing/settings/route'
import { Route as Char123LocaleChar125LandingActivityRouteRouteImport } from './routes/{-$locale}/_landing/activity/route'
import { Route as Char123LocaleChar125ShiponceUsersIndexRouteImport } from './routes/{-$locale}/shiponce/users/index'
import { Route as Char123LocaleChar125ShiponceRolesIndexRouteImport } from './routes/{-$locale}/shiponce/roles/index'
import { Route as Char123LocaleChar125ShiponcePostsIndexRouteImport } from './routes/{-$locale}/shiponce/posts/index'
import { Route as Char123LocaleChar125ShiponceCategoriesIndexRouteImport } from './routes/{-$locale}/shiponce/categories/index'
import { Route as Char123LocaleChar125LandingSettingsIndexRouteImport } from './routes/{-$locale}/_landing/settings/index'
import { Route as Char123LocaleChar125LandingBlogIndexRouteImport } from './routes/{-$locale}/_landing/blog/index'
import { Route as Char123LocaleChar125LandingActivityIndexRouteImport } from './routes/{-$locale}/_landing/activity/index'
import { Route as Char123LocaleChar125AuthVerifyEmailIndexRouteImport } from './routes/{-$locale}/_auth/verify-email/index'
import { Route as Char123LocaleChar125AuthSignUpIndexRouteImport } from './routes/{-$locale}/_auth/sign-up/index'
import { Route as Char123LocaleChar125AuthSignInIndexRouteImport } from './routes/{-$locale}/_auth/sign-in/index'
import { Route as Char123LocaleChar125ShiponceSettingsTabRouteImport } from './routes/{-$locale}/shiponce/settings/$tab'
import { Route as Char123LocaleChar125ShiponcePostsAddRouteImport } from './routes/{-$locale}/shiponce/posts/add'
import { Route as Char123LocaleChar125ShiponceCategoriesAddRouteImport } from './routes/{-$locale}/shiponce/categories/add'
import { Route as Char123LocaleChar125LandingVideoGeneratorSlugRouteImport } from './routes/{-$locale}/_landing/video-generator/$slug'
import { Route as Char123LocaleChar125LandingSettingsSecurityRouteImport } from './routes/{-$locale}/_landing/settings/security'
import { Route as Char123LocaleChar125LandingSettingsProfileRouteImport } from './routes/{-$locale}/_landing/settings/profile'
import { Route as Char123LocaleChar125LandingSettingsPaymentsRouteImport } from './routes/{-$locale}/_landing/settings/payments'
import { Route as Char123LocaleChar125LandingSettingsCreditsRouteImport } from './routes/{-$locale}/_landing/settings/credits'
import { Route as Char123LocaleChar125LandingSettingsBillingRouteImport } from './routes/{-$locale}/_landing/settings/billing'
import { Route as Char123LocaleChar125LandingImageGeneratorSlugRouteImport } from './routes/{-$locale}/_landing/image-generator/$slug'
import { Route as Char123LocaleChar125LandingBlogSlugRouteImport } from './routes/{-$locale}/_landing/blog/$slug'
import { Route as Char123LocaleChar125LandingAiMusicGeneratorRouteImport } from './routes/{-$locale}/_landing/ai/music-generator'
import { Route as Char123LocaleChar125LandingActivityFeedbacksRouteImport } from './routes/{-$locale}/_landing/activity/feedbacks'
import { Route as Char123LocaleChar125LandingActivityAiTasksRouteImport } from './routes/{-$locale}/_landing/activity/ai-tasks'
import { Route as Char123LocaleChar125DocsDocsSplatRouteImport } from './routes/{-$locale}/_docs/docs/$'
import { Route as Char123LocaleChar125ShiponceUsersIdGrantCreditsRouteImport } from './routes/{-$locale}/shiponce/users/$id/grant-credits'
import { Route as Char123LocaleChar125ShiponceUsersIdEditRolesRouteImport } from './routes/{-$locale}/shiponce/users/$id/edit-roles'
import { Route as Char123LocaleChar125ShiponceUsersIdEditRouteImport } from './routes/{-$locale}/shiponce/users/$id/edit'
import { Route as Char123LocaleChar125ShiponceRolesIdEditPermissionsRouteImport } from './routes/{-$locale}/shiponce/roles/$id/edit-permissions'
import { Route as Char123LocaleChar125ShiponceRolesIdEditRouteImport } from './routes/{-$locale}/shiponce/roles/$id/edit'
import { Route as Char123LocaleChar125ShiponcePostsIdEditRouteImport } from './routes/{-$locale}/shiponce/posts/$id/edit'
import { Route as Char123LocaleChar125ShiponceCategoriesIdEditRouteImport } from './routes/{-$locale}/shiponce/categories/$id/edit'
import { Route as Char123LocaleChar125LandingSettingsInvoicesRetrieveRouteImport } from './routes/{-$locale}/_landing/settings/invoices_.retrieve'
import { Route as Char123LocaleChar125LandingSettingsBillingRetrieveRouteImport } from './routes/{-$locale}/_landing/settings/billing_.retrieve'
import { Route as Char123LocaleChar125LandingSettingsBillingCancelRouteImport } from './routes/{-$locale}/_landing/settings/billing_.cancel'
import { Route as Char123LocaleChar125LandingBlogCategorySlugRouteImport } from './routes/{-$locale}/_landing/blog/category/$slug'
import { Route as Char123LocaleChar125LandingActivityAiTasksIdRefreshRouteImport } from './routes/{-$locale}/_landing/activity/ai-tasks_.$id.refresh'

const Char123indexnowKeyChar125DottxtRoute =
  Char123indexnowKeyChar125DottxtRouteImport.update({
    id: '/{$indexnowKey}.txt',
    path: '/{$indexnowKey}.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ConfigRoute =
  Char123LocaleChar125ConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DocsRoute =
  Char123LocaleChar125DocsRouteImport.update({
    id: '/_docs',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ShiponceRouteRoute =
  Char123LocaleChar125ShiponceRouteRouteImport.update({
    id: '/shiponce',
    path: '/shiponce',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125OauthRouteRoute =
  Char123LocaleChar125OauthRouteRouteImport.update({
    id: '/_oauth',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LandingRouteRoute =
  Char123LocaleChar125LandingRouteRouteImport.update({
    id: '/_landing',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthRouteRoute =
  Char123LocaleChar125AuthRouteRouteImport.update({
    id: '/_auth',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ShiponceIndexRoute =
  Char123LocaleChar125ShiponceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125LandingIndexRoute =
  Char123LocaleChar125LandingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceSubscriptionsRoute =
  Char123LocaleChar125ShiponceSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponcePermissionsRoute =
  Char123LocaleChar125ShiponcePermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponcePaymentsRoute =
  Char123LocaleChar125ShiponcePaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceNoPermissionRoute =
  Char123LocaleChar125ShiponceNoPermissionRouteImport.update({
    id: '/no-permission',
    path: '/no-permission',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceCreditsRoute =
  Char123LocaleChar125ShiponceCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceAiTasksRoute =
  Char123LocaleChar125ShiponceAiTasksRouteImport.update({
    id: '/ai-tasks',
    path: '/ai-tasks',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125OauthAuthPopupRoute =
  Char123LocaleChar125OauthAuthPopupRouteImport.update({
    id: '/auth-popup',
    path: '/auth-popup',
    getParentRoute: () => Char123LocaleChar125OauthRouteRoute,
  } as any)
const Char123LocaleChar125OauthAuthCallbackRoute =
  Char123LocaleChar125OauthAuthCallbackRouteImport.update({
    id: '/auth-callback',
    path: '/auth-callback',
    getParentRoute: () => Char123LocaleChar125OauthRouteRoute,
  } as any)
const Char123LocaleChar125LandingVideoGeneratorRoute =
  Char123LocaleChar125LandingVideoGeneratorRouteImport.update({
    id: '/video-generator',
    path: '/video-generator',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingUpdatesRoute =
  Char123LocaleChar125LandingUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingTermsOfServiceRoute =
  Char123LocaleChar125LandingTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingShowcasesRoute =
  Char123LocaleChar125LandingShowcasesRouteImport.update({
    id: '/showcases',
    path: '/showcases',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingShowcaseRoute =
  Char123LocaleChar125LandingShowcaseRouteImport.update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingPrivacyPolicyRoute =
  Char123LocaleChar125LandingPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingPricingRoute =
  Char123LocaleChar125LandingPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingImageGeneratorRoute =
  Char123LocaleChar125LandingImageGeneratorRouteImport.update({
    id: '/image-generator',
    path: '/image-generator',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingGenerateRoute =
  Char123LocaleChar125LandingGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingFeedbackRoute =
  Char123LocaleChar125LandingFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingExamplesRoute =
  Char123LocaleChar125LandingExamplesRouteImport.update({
    id: '/examples',
    path: '/examples',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingSplatRoute =
  Char123LocaleChar125LandingSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125AuthNoPermissionRoute =
  Char123LocaleChar125AuthNoPermissionRouteImport.update({
    id: '/no-permission',
    path: '/no-permission',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const ApiProxyFileRoute = ApiProxyFileRouteImport.update({
  id: '/api/proxy/file',
  path: '/api/proxy/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCallbackRoute = ApiPaymentCallbackRouteImport.update({
  id: '/api/payment/callback',
  path: '/api/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125LandingSettingsRouteRoute =
  Char123LocaleChar125LandingSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingActivityRouteRoute =
  Char123LocaleChar125LandingActivityRouteRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceUsersIndexRoute =
  Char123LocaleChar125ShiponceUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceRolesIndexRoute =
  Char123LocaleChar125ShiponceRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponcePostsIndexRoute =
  Char123LocaleChar125ShiponcePostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceCategoriesIndexRoute =
  Char123LocaleChar125ShiponceCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125LandingSettingsIndexRoute =
  Char123LocaleChar125LandingSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingBlogIndexRoute =
  Char123LocaleChar125LandingBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingActivityIndexRoute =
  Char123LocaleChar125LandingActivityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125LandingActivityRouteRoute,
  } as any)
const Char123LocaleChar125AuthVerifyEmailIndexRoute =
  Char123LocaleChar125AuthVerifyEmailIndexRouteImport.update({
    id: '/verify-email/',
    path: '/verify-email/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125AuthSignUpIndexRoute =
  Char123LocaleChar125AuthSignUpIndexRouteImport.update({
    id: '/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125AuthSignInIndexRoute =
  Char123LocaleChar125AuthSignInIndexRouteImport.update({
    id: '/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceSettingsTabRoute =
  Char123LocaleChar125ShiponceSettingsTabRouteImport.update({
    id: '/settings/$tab',
    path: '/settings/$tab',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponcePostsAddRoute =
  Char123LocaleChar125ShiponcePostsAddRouteImport.update({
    id: '/posts/add',
    path: '/posts/add',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceCategoriesAddRoute =
  Char123LocaleChar125ShiponceCategoriesAddRouteImport.update({
    id: '/categories/add',
    path: '/categories/add',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125LandingVideoGeneratorSlugRoute =
  Char123LocaleChar125LandingVideoGeneratorSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => Char123LocaleChar125LandingVideoGeneratorRoute,
  } as any)
const Char123LocaleChar125LandingSettingsSecurityRoute =
  Char123LocaleChar125LandingSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingSettingsProfileRoute =
  Char123LocaleChar125LandingSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingSettingsPaymentsRoute =
  Char123LocaleChar125LandingSettingsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingSettingsCreditsRoute =
  Char123LocaleChar125LandingSettingsCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingSettingsBillingRoute =
  Char123LocaleChar125LandingSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingImageGeneratorSlugRoute =
  Char123LocaleChar125LandingImageGeneratorSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => Char123LocaleChar125LandingImageGeneratorRoute,
  } as any)
const Char123LocaleChar125LandingBlogSlugRoute =
  Char123LocaleChar125LandingBlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingAiMusicGeneratorRoute =
  Char123LocaleChar125LandingAiMusicGeneratorRouteImport.update({
    id: '/ai/music-generator',
    path: '/ai/music-generator',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingActivityFeedbacksRoute =
  Char123LocaleChar125LandingActivityFeedbacksRouteImport.update({
    id: '/feedbacks',
    path: '/feedbacks',
    getParentRoute: () => Char123LocaleChar125LandingActivityRouteRoute,
  } as any)
const Char123LocaleChar125LandingActivityAiTasksRoute =
  Char123LocaleChar125LandingActivityAiTasksRouteImport.update({
    id: '/ai-tasks',
    path: '/ai-tasks',
    getParentRoute: () => Char123LocaleChar125LandingActivityRouteRoute,
  } as any)
const Char123LocaleChar125DocsDocsSplatRoute =
  Char123LocaleChar125DocsDocsSplatRouteImport.update({
    id: '/docs/$',
    path: '/docs/$',
    getParentRoute: () => Char123LocaleChar125DocsRoute,
  } as any)
const Char123LocaleChar125ShiponceUsersIdGrantCreditsRoute =
  Char123LocaleChar125ShiponceUsersIdGrantCreditsRouteImport.update({
    id: '/users/$id/grant-credits',
    path: '/users/$id/grant-credits',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceUsersIdEditRolesRoute =
  Char123LocaleChar125ShiponceUsersIdEditRolesRouteImport.update({
    id: '/users/$id/edit-roles',
    path: '/users/$id/edit-roles',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceUsersIdEditRoute =
  Char123LocaleChar125ShiponceUsersIdEditRouteImport.update({
    id: '/users/$id/edit',
    path: '/users/$id/edit',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceRolesIdEditPermissionsRoute =
  Char123LocaleChar125ShiponceRolesIdEditPermissionsRouteImport.update({
    id: '/roles/$id/edit-permissions',
    path: '/roles/$id/edit-permissions',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceRolesIdEditRoute =
  Char123LocaleChar125ShiponceRolesIdEditRouteImport.update({
    id: '/roles/$id/edit',
    path: '/roles/$id/edit',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponcePostsIdEditRoute =
  Char123LocaleChar125ShiponcePostsIdEditRouteImport.update({
    id: '/posts/$id/edit',
    path: '/posts/$id/edit',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125ShiponceCategoriesIdEditRoute =
  Char123LocaleChar125ShiponceCategoriesIdEditRouteImport.update({
    id: '/categories/$id/edit',
    path: '/categories/$id/edit',
    getParentRoute: () => Char123LocaleChar125ShiponceRouteRoute,
  } as any)
const Char123LocaleChar125LandingSettingsInvoicesRetrieveRoute =
  Char123LocaleChar125LandingSettingsInvoicesRetrieveRouteImport.update({
    id: '/invoices_/retrieve',
    path: '/invoices/retrieve',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingSettingsBillingRetrieveRoute =
  Char123LocaleChar125LandingSettingsBillingRetrieveRouteImport.update({
    id: '/billing_/retrieve',
    path: '/billing/retrieve',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingSettingsBillingCancelRoute =
  Char123LocaleChar125LandingSettingsBillingCancelRouteImport.update({
    id: '/billing_/cancel',
    path: '/billing/cancel',
    getParentRoute: () => Char123LocaleChar125LandingSettingsRouteRoute,
  } as any)
const Char123LocaleChar125LandingBlogCategorySlugRoute =
  Char123LocaleChar125LandingBlogCategorySlugRouteImport.update({
    id: '/blog/category/$slug',
    path: '/blog/category/$slug',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingActivityAiTasksIdRefreshRoute =
  Char123LocaleChar125LandingActivityAiTasksIdRefreshRouteImport.update({
    id: '/ai-tasks_/$id/refresh',
    path: '/ai-tasks/$id/refresh',
    getParentRoute: () => Char123LocaleChar125LandingActivityRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125DocsRouteWithChildren
  '/{$indexnowKey}.txt': typeof Char123indexnowKeyChar125DottxtRoute
  '/{-$locale}/shiponce': typeof Char123LocaleChar125ShiponceRouteRouteWithChildren
  '/{-$locale}/config': typeof Char123LocaleChar125ConfigRoute
  '/{-$locale}/activity': typeof Char123LocaleChar125LandingActivityRouteRouteWithChildren
  '/{-$locale}/settings': typeof Char123LocaleChar125LandingSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/proxy/file': typeof ApiProxyFileRoute
  '/{-$locale}/no-permission': typeof Char123LocaleChar125AuthNoPermissionRoute
  '/{-$locale}/$': typeof Char123LocaleChar125LandingSplatRoute
  '/{-$locale}/examples': typeof Char123LocaleChar125LandingExamplesRoute
  '/{-$locale}/feedback': typeof Char123LocaleChar125LandingFeedbackRoute
  '/{-$locale}/generate': typeof Char123LocaleChar125LandingGenerateRoute
  '/{-$locale}/image-generator': typeof Char123LocaleChar125LandingImageGeneratorRouteWithChildren
  '/{-$locale}/pricing': typeof Char123LocaleChar125LandingPricingRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125LandingPrivacyPolicyRoute
  '/{-$locale}/showcase': typeof Char123LocaleChar125LandingShowcaseRoute
  '/{-$locale}/showcases': typeof Char123LocaleChar125LandingShowcasesRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125LandingTermsOfServiceRoute
  '/{-$locale}/updates': typeof Char123LocaleChar125LandingUpdatesRoute
  '/{-$locale}/video-generator': typeof Char123LocaleChar125LandingVideoGeneratorRouteWithChildren
  '/{-$locale}/auth-callback': typeof Char123LocaleChar125OauthAuthCallbackRoute
  '/{-$locale}/auth-popup': typeof Char123LocaleChar125OauthAuthPopupRoute
  '/{-$locale}/shiponce/ai-tasks': typeof Char123LocaleChar125ShiponceAiTasksRoute
  '/{-$locale}/shiponce/credits': typeof Char123LocaleChar125ShiponceCreditsRoute
  '/{-$locale}/shiponce/no-permission': typeof Char123LocaleChar125ShiponceNoPermissionRoute
  '/{-$locale}/shiponce/payments': typeof Char123LocaleChar125ShiponcePaymentsRoute
  '/{-$locale}/shiponce/permissions': typeof Char123LocaleChar125ShiponcePermissionsRoute
  '/{-$locale}/shiponce/subscriptions': typeof Char123LocaleChar125ShiponceSubscriptionsRoute
  '/{-$locale}/': typeof Char123LocaleChar125LandingIndexRoute
  '/{-$locale}/shiponce/': typeof Char123LocaleChar125ShiponceIndexRoute
  '/{-$locale}/docs/$': typeof Char123LocaleChar125DocsDocsSplatRoute
  '/{-$locale}/activity/ai-tasks': typeof Char123LocaleChar125LandingActivityAiTasksRoute
  '/{-$locale}/activity/feedbacks': typeof Char123LocaleChar125LandingActivityFeedbacksRoute
  '/{-$locale}/ai/music-generator': typeof Char123LocaleChar125LandingAiMusicGeneratorRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125LandingBlogSlugRoute
  '/{-$locale}/image-generator/$slug': typeof Char123LocaleChar125LandingImageGeneratorSlugRoute
  '/{-$locale}/settings/billing': typeof Char123LocaleChar125LandingSettingsBillingRoute
  '/{-$locale}/settings/credits': typeof Char123LocaleChar125LandingSettingsCreditsRoute
  '/{-$locale}/settings/payments': typeof Char123LocaleChar125LandingSettingsPaymentsRoute
  '/{-$locale}/settings/profile': typeof Char123LocaleChar125LandingSettingsProfileRoute
  '/{-$locale}/settings/security': typeof Char123LocaleChar125LandingSettingsSecurityRoute
  '/{-$locale}/video-generator/$slug': typeof Char123LocaleChar125LandingVideoGeneratorSlugRoute
  '/{-$locale}/shiponce/categories/add': typeof Char123LocaleChar125ShiponceCategoriesAddRoute
  '/{-$locale}/shiponce/posts/add': typeof Char123LocaleChar125ShiponcePostsAddRoute
  '/{-$locale}/shiponce/settings/$tab': typeof Char123LocaleChar125ShiponceSettingsTabRoute
  '/{-$locale}/sign-in/': typeof Char123LocaleChar125AuthSignInIndexRoute
  '/{-$locale}/sign-up/': typeof Char123LocaleChar125AuthSignUpIndexRoute
  '/{-$locale}/verify-email/': typeof Char123LocaleChar125AuthVerifyEmailIndexRoute
  '/{-$locale}/activity/': typeof Char123LocaleChar125LandingActivityIndexRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125LandingBlogIndexRoute
  '/{-$locale}/settings/': typeof Char123LocaleChar125LandingSettingsIndexRoute
  '/{-$locale}/shiponce/categories/': typeof Char123LocaleChar125ShiponceCategoriesIndexRoute
  '/{-$locale}/shiponce/posts/': typeof Char123LocaleChar125ShiponcePostsIndexRoute
  '/{-$locale}/shiponce/roles/': typeof Char123LocaleChar125ShiponceRolesIndexRoute
  '/{-$locale}/shiponce/users/': typeof Char123LocaleChar125ShiponceUsersIndexRoute
  '/{-$locale}/blog/category/$slug': typeof Char123LocaleChar125LandingBlogCategorySlugRoute
  '/{-$locale}/settings/billing/cancel': typeof Char123LocaleChar125LandingSettingsBillingCancelRoute
  '/{-$locale}/settings/billing/retrieve': typeof Char123LocaleChar125LandingSettingsBillingRetrieveRoute
  '/{-$locale}/settings/invoices/retrieve': typeof Char123LocaleChar125LandingSettingsInvoicesRetrieveRoute
  '/{-$locale}/shiponce/categories/$id/edit': typeof Char123LocaleChar125ShiponceCategoriesIdEditRoute
  '/{-$locale}/shiponce/posts/$id/edit': typeof Char123LocaleChar125ShiponcePostsIdEditRoute
  '/{-$locale}/shiponce/roles/$id/edit': typeof Char123LocaleChar125ShiponceRolesIdEditRoute
  '/{-$locale}/shiponce/roles/$id/edit-permissions': typeof Char123LocaleChar125ShiponceRolesIdEditPermissionsRoute
  '/{-$locale}/shiponce/users/$id/edit': typeof Char123LocaleChar125ShiponceUsersIdEditRoute
  '/{-$locale}/shiponce/users/$id/edit-roles': typeof Char123LocaleChar125ShiponceUsersIdEditRolesRoute
  '/{-$locale}/shiponce/users/$id/grant-credits': typeof Char123LocaleChar125ShiponceUsersIdGrantCreditsRoute
  '/{-$locale}/activity/ai-tasks/$id/refresh': typeof Char123LocaleChar125LandingActivityAiTasksIdRefreshRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125LandingIndexRoute
  '/{$indexnowKey}.txt': typeof Char123indexnowKeyChar125DottxtRoute
  '/{-$locale}/config': typeof Char123LocaleChar125ConfigRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/proxy/file': typeof ApiProxyFileRoute
  '/{-$locale}/no-permission': typeof Char123LocaleChar125AuthNoPermissionRoute
  '/{-$locale}/$': typeof Char123LocaleChar125LandingSplatRoute
  '/{-$locale}/examples': typeof Char123LocaleChar125LandingExamplesRoute
  '/{-$locale}/feedback': typeof Char123LocaleChar125LandingFeedbackRoute
  '/{-$locale}/generate': typeof Char123LocaleChar125LandingGenerateRoute
  '/{-$locale}/image-generator': typeof Char123LocaleChar125LandingImageGeneratorRouteWithChildren
  '/{-$locale}/pricing': typeof Char123LocaleChar125LandingPricingRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125LandingPrivacyPolicyRoute
  '/{-$locale}/showcase': typeof Char123LocaleChar125LandingShowcaseRoute
  '/{-$locale}/showcases': typeof Char123LocaleChar125LandingShowcasesRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125LandingTermsOfServiceRoute
  '/{-$locale}/updates': typeof Char123LocaleChar125LandingUpdatesRoute
  '/{-$locale}/video-generator': typeof Char123LocaleChar125LandingVideoGeneratorRouteWithChildren
  '/{-$locale}/auth-callback': typeof Char123LocaleChar125OauthAuthCallbackRoute
  '/{-$locale}/auth-popup': typeof Char123LocaleChar125OauthAuthPopupRoute
  '/{-$locale}/shiponce/ai-tasks': typeof Char123LocaleChar125ShiponceAiTasksRoute
  '/{-$locale}/shiponce/credits': typeof Char123LocaleChar125ShiponceCreditsRoute
  '/{-$locale}/shiponce/no-permission': typeof Char123LocaleChar125ShiponceNoPermissionRoute
  '/{-$locale}/shiponce/payments': typeof Char123LocaleChar125ShiponcePaymentsRoute
  '/{-$locale}/shiponce/permissions': typeof Char123LocaleChar125ShiponcePermissionsRoute
  '/{-$locale}/shiponce/subscriptions': typeof Char123LocaleChar125ShiponceSubscriptionsRoute
  '/{-$locale}/shiponce': typeof Char123LocaleChar125ShiponceIndexRoute
  '/{-$locale}/docs/$': typeof Char123LocaleChar125DocsDocsSplatRoute
  '/{-$locale}/activity/ai-tasks': typeof Char123LocaleChar125LandingActivityAiTasksRoute
  '/{-$locale}/activity/feedbacks': typeof Char123LocaleChar125LandingActivityFeedbacksRoute
  '/{-$locale}/ai/music-generator': typeof Char123LocaleChar125LandingAiMusicGeneratorRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125LandingBlogSlugRoute
  '/{-$locale}/image-generator/$slug': typeof Char123LocaleChar125LandingImageGeneratorSlugRoute
  '/{-$locale}/settings/billing': typeof Char123LocaleChar125LandingSettingsBillingRoute
  '/{-$locale}/settings/credits': typeof Char123LocaleChar125LandingSettingsCreditsRoute
  '/{-$locale}/settings/payments': typeof Char123LocaleChar125LandingSettingsPaymentsRoute
  '/{-$locale}/settings/profile': typeof Char123LocaleChar125LandingSettingsProfileRoute
  '/{-$locale}/settings/security': typeof Char123LocaleChar125LandingSettingsSecurityRoute
  '/{-$locale}/video-generator/$slug': typeof Char123LocaleChar125LandingVideoGeneratorSlugRoute
  '/{-$locale}/shiponce/categories/add': typeof Char123LocaleChar125ShiponceCategoriesAddRoute
  '/{-$locale}/shiponce/posts/add': typeof Char123LocaleChar125ShiponcePostsAddRoute
  '/{-$locale}/shiponce/settings/$tab': typeof Char123LocaleChar125ShiponceSettingsTabRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125AuthSignInIndexRoute
  '/{-$locale}/sign-up': typeof Char123LocaleChar125AuthSignUpIndexRoute
  '/{-$locale}/verify-email': typeof Char123LocaleChar125AuthVerifyEmailIndexRoute
  '/{-$locale}/activity': typeof Char123LocaleChar125LandingActivityIndexRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125LandingBlogIndexRoute
  '/{-$locale}/settings': typeof Char123LocaleChar125LandingSettingsIndexRoute
  '/{-$locale}/shiponce/categories': typeof Char123LocaleChar125ShiponceCategoriesIndexRoute
  '/{-$locale}/shiponce/posts': typeof Char123LocaleChar125ShiponcePostsIndexRoute
  '/{-$locale}/shiponce/roles': typeof Char123LocaleChar125ShiponceRolesIndexRoute
  '/{-$locale}/shiponce/users': typeof Char123LocaleChar125ShiponceUsersIndexRoute
  '/{-$locale}/blog/category/$slug': typeof Char123LocaleChar125LandingBlogCategorySlugRoute
  '/{-$locale}/settings/billing/cancel': typeof Char123LocaleChar125LandingSettingsBillingCancelRoute
  '/{-$locale}/settings/billing/retrieve': typeof Char123LocaleChar125LandingSettingsBillingRetrieveRoute
  '/{-$locale}/settings/invoices/retrieve': typeof Char123LocaleChar125LandingSettingsInvoicesRetrieveRoute
  '/{-$locale}/shiponce/categories/$id/edit': typeof Char123LocaleChar125ShiponceCategoriesIdEditRoute
  '/{-$locale}/shiponce/posts/$id/edit': typeof Char123LocaleChar125ShiponcePostsIdEditRoute
  '/{-$locale}/shiponce/roles/$id/edit': typeof Char123LocaleChar125ShiponceRolesIdEditRoute
  '/{-$locale}/shiponce/roles/$id/edit-permissions': typeof Char123LocaleChar125ShiponceRolesIdEditPermissionsRoute
  '/{-$locale}/shiponce/users/$id/edit': typeof Char123LocaleChar125ShiponceUsersIdEditRoute
  '/{-$locale}/shiponce/users/$id/edit-roles': typeof Char123LocaleChar125ShiponceUsersIdEditRolesRoute
  '/{-$locale}/shiponce/users/$id/grant-credits': typeof Char123LocaleChar125ShiponceUsersIdGrantCreditsRoute
  '/{-$locale}/activity/ai-tasks/$id/refresh': typeof Char123LocaleChar125LandingActivityAiTasksIdRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{$indexnowKey}.txt': typeof Char123indexnowKeyChar125DottxtRoute
  '/{-$locale}/_auth': typeof Char123LocaleChar125AuthRouteRouteWithChildren
  '/{-$locale}/_landing': typeof Char123LocaleChar125LandingRouteRouteWithChildren
  '/{-$locale}/_oauth': typeof Char123LocaleChar125OauthRouteRouteWithChildren
  '/{-$locale}/shiponce': typeof Char123LocaleChar125ShiponceRouteRouteWithChildren
  '/{-$locale}/_docs': typeof Char123LocaleChar125DocsRouteWithChildren
  '/{-$locale}/config': typeof Char123LocaleChar125ConfigRoute
  '/{-$locale}/_landing/activity': typeof Char123LocaleChar125LandingActivityRouteRouteWithChildren
  '/{-$locale}/_landing/settings': typeof Char123LocaleChar125LandingSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/proxy/file': typeof ApiProxyFileRoute
  '/{-$locale}/_auth/no-permission': typeof Char123LocaleChar125AuthNoPermissionRoute
  '/{-$locale}/_landing/$': typeof Char123LocaleChar125LandingSplatRoute
  '/{-$locale}/_landing/examples': typeof Char123LocaleChar125LandingExamplesRoute
  '/{-$locale}/_landing/feedback': typeof Char123LocaleChar125LandingFeedbackRoute
  '/{-$locale}/_landing/generate': typeof Char123LocaleChar125LandingGenerateRoute
  '/{-$locale}/_landing/image-generator': typeof Char123LocaleChar125LandingImageGeneratorRouteWithChildren
  '/{-$locale}/_landing/pricing': typeof Char123LocaleChar125LandingPricingRoute
  '/{-$locale}/_landing/privacy-policy': typeof Char123LocaleChar125LandingPrivacyPolicyRoute
  '/{-$locale}/_landing/showcase': typeof Char123LocaleChar125LandingShowcaseRoute
  '/{-$locale}/_landing/showcases': typeof Char123LocaleChar125LandingShowcasesRoute
  '/{-$locale}/_landing/terms-of-service': typeof Char123LocaleChar125LandingTermsOfServiceRoute
  '/{-$locale}/_landing/updates': typeof Char123LocaleChar125LandingUpdatesRoute
  '/{-$locale}/_landing/video-generator': typeof Char123LocaleChar125LandingVideoGeneratorRouteWithChildren
  '/{-$locale}/_oauth/auth-callback': typeof Char123LocaleChar125OauthAuthCallbackRoute
  '/{-$locale}/_oauth/auth-popup': typeof Char123LocaleChar125OauthAuthPopupRoute
  '/{-$locale}/shiponce/ai-tasks': typeof Char123LocaleChar125ShiponceAiTasksRoute
  '/{-$locale}/shiponce/credits': typeof Char123LocaleChar125ShiponceCreditsRoute
  '/{-$locale}/shiponce/no-permission': typeof Char123LocaleChar125ShiponceNoPermissionRoute
  '/{-$locale}/shiponce/payments': typeof Char123LocaleChar125ShiponcePaymentsRoute
  '/{-$locale}/shiponce/permissions': typeof Char123LocaleChar125ShiponcePermissionsRoute
  '/{-$locale}/shiponce/subscriptions': typeof Char123LocaleChar125ShiponceSubscriptionsRoute
  '/{-$locale}/_landing/': typeof Char123LocaleChar125LandingIndexRoute
  '/{-$locale}/shiponce/': typeof Char123LocaleChar125ShiponceIndexRoute
  '/{-$locale}/_docs/docs/$': typeof Char123LocaleChar125DocsDocsSplatRoute
  '/{-$locale}/_landing/activity/ai-tasks': typeof Char123LocaleChar125LandingActivityAiTasksRoute
  '/{-$locale}/_landing/activity/feedbacks': typeof Char123LocaleChar125LandingActivityFeedbacksRoute
  '/{-$locale}/_landing/ai/music-generator': typeof Char123LocaleChar125LandingAiMusicGeneratorRoute
  '/{-$locale}/_landing/blog/$slug': typeof Char123LocaleChar125LandingBlogSlugRoute
  '/{-$locale}/_landing/image-generator/$slug': typeof Char123LocaleChar125LandingImageGeneratorSlugRoute
  '/{-$locale}/_landing/settings/billing': typeof Char123LocaleChar125LandingSettingsBillingRoute
  '/{-$locale}/_landing/settings/credits': typeof Char123LocaleChar125LandingSettingsCreditsRoute
  '/{-$locale}/_landing/settings/payments': typeof Char123LocaleChar125LandingSettingsPaymentsRoute
  '/{-$locale}/_landing/settings/profile': typeof Char123LocaleChar125LandingSettingsProfileRoute
  '/{-$locale}/_landing/settings/security': typeof Char123LocaleChar125LandingSettingsSecurityRoute
  '/{-$locale}/_landing/video-generator/$slug': typeof Char123LocaleChar125LandingVideoGeneratorSlugRoute
  '/{-$locale}/shiponce/categories/add': typeof Char123LocaleChar125ShiponceCategoriesAddRoute
  '/{-$locale}/shiponce/posts/add': typeof Char123LocaleChar125ShiponcePostsAddRoute
  '/{-$locale}/shiponce/settings/$tab': typeof Char123LocaleChar125ShiponceSettingsTabRoute
  '/{-$locale}/_auth/sign-in/': typeof Char123LocaleChar125AuthSignInIndexRoute
  '/{-$locale}/_auth/sign-up/': typeof Char123LocaleChar125AuthSignUpIndexRoute
  '/{-$locale}/_auth/verify-email/': typeof Char123LocaleChar125AuthVerifyEmailIndexRoute
  '/{-$locale}/_landing/activity/': typeof Char123LocaleChar125LandingActivityIndexRoute
  '/{-$locale}/_landing/blog/': typeof Char123LocaleChar125LandingBlogIndexRoute
  '/{-$locale}/_landing/settings/': typeof Char123LocaleChar125LandingSettingsIndexRoute
  '/{-$locale}/shiponce/categories/': typeof Char123LocaleChar125ShiponceCategoriesIndexRoute
  '/{-$locale}/shiponce/posts/': typeof Char123LocaleChar125ShiponcePostsIndexRoute
  '/{-$locale}/shiponce/roles/': typeof Char123LocaleChar125ShiponceRolesIndexRoute
  '/{-$locale}/shiponce/users/': typeof Char123LocaleChar125ShiponceUsersIndexRoute
  '/{-$locale}/_landing/blog/category/$slug': typeof Char123LocaleChar125LandingBlogCategorySlugRoute
  '/{-$locale}/_landing/settings/billing_/cancel': typeof Char123LocaleChar125LandingSettingsBillingCancelRoute
  '/{-$locale}/_landing/settings/billing_/retrieve': typeof Char123LocaleChar125LandingSettingsBillingRetrieveRoute
  '/{-$locale}/_landing/settings/invoices_/retrieve': typeof Char123LocaleChar125LandingSettingsInvoicesRetrieveRoute
  '/{-$locale}/shiponce/categories/$id/edit': typeof Char123LocaleChar125ShiponceCategoriesIdEditRoute
  '/{-$locale}/shiponce/posts/$id/edit': typeof Char123LocaleChar125ShiponcePostsIdEditRoute
  '/{-$locale}/shiponce/roles/$id/edit': typeof Char123LocaleChar125ShiponceRolesIdEditRoute
  '/{-$locale}/shiponce/roles/$id/edit-permissions': typeof Char123LocaleChar125ShiponceRolesIdEditPermissionsRoute
  '/{-$locale}/shiponce/users/$id/edit': typeof Char123LocaleChar125ShiponceUsersIdEditRoute
  '/{-$locale}/shiponce/users/$id/edit-roles': typeof Char123LocaleChar125ShiponceUsersIdEditRolesRoute
  '/{-$locale}/shiponce/users/$id/grant-credits': typeof Char123LocaleChar125ShiponceUsersIdGrantCreditsRoute
  '/{-$locale}/_landing/activity/ai-tasks_/$id/refresh': typeof Char123LocaleChar125LandingActivityAiTasksIdRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{$indexnowKey}.txt'
    | '/{-$locale}/shiponce'
    | '/{-$locale}/config'
    | '/{-$locale}/activity'
    | '/{-$locale}/settings'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/proxy/file'
    | '/{-$locale}/no-permission'
    | '/{-$locale}/$'
    | '/{-$locale}/examples'
    | '/{-$locale}/feedback'
    | '/{-$locale}/generate'
    | '/{-$locale}/image-generator'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/showcase'
    | '/{-$locale}/showcases'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/updates'
    | '/{-$locale}/video-generator'
    | '/{-$locale}/auth-callback'
    | '/{-$locale}/auth-popup'
    | '/{-$locale}/shiponce/ai-tasks'
    | '/{-$locale}/shiponce/credits'
    | '/{-$locale}/shiponce/no-permission'
    | '/{-$locale}/shiponce/payments'
    | '/{-$locale}/shiponce/permissions'
    | '/{-$locale}/shiponce/subscriptions'
    | '/{-$locale}/'
    | '/{-$locale}/shiponce/'
    | '/{-$locale}/docs/$'
    | '/{-$locale}/activity/ai-tasks'
    | '/{-$locale}/activity/feedbacks'
    | '/{-$locale}/ai/music-generator'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/image-generator/$slug'
    | '/{-$locale}/settings/billing'
    | '/{-$locale}/settings/credits'
    | '/{-$locale}/settings/payments'
    | '/{-$locale}/settings/profile'
    | '/{-$locale}/settings/security'
    | '/{-$locale}/video-generator/$slug'
    | '/{-$locale}/shiponce/categories/add'
    | '/{-$locale}/shiponce/posts/add'
    | '/{-$locale}/shiponce/settings/$tab'
    | '/{-$locale}/sign-in/'
    | '/{-$locale}/sign-up/'
    | '/{-$locale}/verify-email/'
    | '/{-$locale}/activity/'
    | '/{-$locale}/blog/'
    | '/{-$locale}/settings/'
    | '/{-$locale}/shiponce/categories/'
    | '/{-$locale}/shiponce/posts/'
    | '/{-$locale}/shiponce/roles/'
    | '/{-$locale}/shiponce/users/'
    | '/{-$locale}/blog/category/$slug'
    | '/{-$locale}/settings/billing/cancel'
    | '/{-$locale}/settings/billing/retrieve'
    | '/{-$locale}/settings/invoices/retrieve'
    | '/{-$locale}/shiponce/categories/$id/edit'
    | '/{-$locale}/shiponce/posts/$id/edit'
    | '/{-$locale}/shiponce/roles/$id/edit'
    | '/{-$locale}/shiponce/roles/$id/edit-permissions'
    | '/{-$locale}/shiponce/users/$id/edit'
    | '/{-$locale}/shiponce/users/$id/edit-roles'
    | '/{-$locale}/shiponce/users/$id/grant-credits'
    | '/{-$locale}/activity/ai-tasks/$id/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{$indexnowKey}.txt'
    | '/{-$locale}/config'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/proxy/file'
    | '/{-$locale}/no-permission'
    | '/{-$locale}/$'
    | '/{-$locale}/examples'
    | '/{-$locale}/feedback'
    | '/{-$locale}/generate'
    | '/{-$locale}/image-generator'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/showcase'
    | '/{-$locale}/showcases'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/updates'
    | '/{-$locale}/video-generator'
    | '/{-$locale}/auth-callback'
    | '/{-$locale}/auth-popup'
    | '/{-$locale}/shiponce/ai-tasks'
    | '/{-$locale}/shiponce/credits'
    | '/{-$locale}/shiponce/no-permission'
    | '/{-$locale}/shiponce/payments'
    | '/{-$locale}/shiponce/permissions'
    | '/{-$locale}/shiponce/subscriptions'
    | '/{-$locale}/shiponce'
    | '/{-$locale}/docs/$'
    | '/{-$locale}/activity/ai-tasks'
    | '/{-$locale}/activity/feedbacks'
    | '/{-$locale}/ai/music-generator'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/image-generator/$slug'
    | '/{-$locale}/settings/billing'
    | '/{-$locale}/settings/credits'
    | '/{-$locale}/settings/payments'
    | '/{-$locale}/settings/profile'
    | '/{-$locale}/settings/security'
    | '/{-$locale}/video-generator/$slug'
    | '/{-$locale}/shiponce/categories/add'
    | '/{-$locale}/shiponce/posts/add'
    | '/{-$locale}/shiponce/settings/$tab'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/sign-up'
    | '/{-$locale}/verify-email'
    | '/{-$locale}/activity'
    | '/{-$locale}/blog'
    | '/{-$locale}/settings'
    | '/{-$locale}/shiponce/categories'
    | '/{-$locale}/shiponce/posts'
    | '/{-$locale}/shiponce/roles'
    | '/{-$locale}/shiponce/users'
    | '/{-$locale}/blog/category/$slug'
    | '/{-$locale}/settings/billing/cancel'
    | '/{-$locale}/settings/billing/retrieve'
    | '/{-$locale}/settings/invoices/retrieve'
    | '/{-$locale}/shiponce/categories/$id/edit'
    | '/{-$locale}/shiponce/posts/$id/edit'
    | '/{-$locale}/shiponce/roles/$id/edit'
    | '/{-$locale}/shiponce/roles/$id/edit-permissions'
    | '/{-$locale}/shiponce/users/$id/edit'
    | '/{-$locale}/shiponce/users/$id/edit-roles'
    | '/{-$locale}/shiponce/users/$id/grant-credits'
    | '/{-$locale}/activity/ai-tasks/$id/refresh'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{$indexnowKey}.txt'
    | '/{-$locale}/_auth'
    | '/{-$locale}/_landing'
    | '/{-$locale}/_oauth'
    | '/{-$locale}/shiponce'
    | '/{-$locale}/_docs'
    | '/{-$locale}/config'
    | '/{-$locale}/_landing/activity'
    | '/{-$locale}/_landing/settings'
    | '/api/auth/$'
    | '/api/payment/callback'
    | '/api/proxy/file'
    | '/{-$locale}/_auth/no-permission'
    | '/{-$locale}/_landing/$'
    | '/{-$locale}/_landing/examples'
    | '/{-$locale}/_landing/feedback'
    | '/{-$locale}/_landing/generate'
    | '/{-$locale}/_landing/image-generator'
    | '/{-$locale}/_landing/pricing'
    | '/{-$locale}/_landing/privacy-policy'
    | '/{-$locale}/_landing/showcase'
    | '/{-$locale}/_landing/showcases'
    | '/{-$locale}/_landing/terms-of-service'
    | '/{-$locale}/_landing/updates'
    | '/{-$locale}/_landing/video-generator'
    | '/{-$locale}/_oauth/auth-callback'
    | '/{-$locale}/_oauth/auth-popup'
    | '/{-$locale}/shiponce/ai-tasks'
    | '/{-$locale}/shiponce/credits'
    | '/{-$locale}/shiponce/no-permission'
    | '/{-$locale}/shiponce/payments'
    | '/{-$locale}/shiponce/permissions'
    | '/{-$locale}/shiponce/subscriptions'
    | '/{-$locale}/_landing/'
    | '/{-$locale}/shiponce/'
    | '/{-$locale}/_docs/docs/$'
    | '/{-$locale}/_landing/activity/ai-tasks'
    | '/{-$locale}/_landing/activity/feedbacks'
    | '/{-$locale}/_landing/ai/music-generator'
    | '/{-$locale}/_landing/blog/$slug'
    | '/{-$locale}/_landing/image-generator/$slug'
    | '/{-$locale}/_landing/settings/billing'
    | '/{-$locale}/_landing/settings/credits'
    | '/{-$locale}/_landing/settings/payments'
    | '/{-$locale}/_landing/settings/profile'
    | '/{-$locale}/_landing/settings/security'
    | '/{-$locale}/_landing/video-generator/$slug'
    | '/{-$locale}/shiponce/categories/add'
    | '/{-$locale}/shiponce/posts/add'
    | '/{-$locale}/shiponce/settings/$tab'
    | '/{-$locale}/_auth/sign-in/'
    | '/{-$locale}/_auth/sign-up/'
    | '/{-$locale}/_auth/verify-email/'
    | '/{-$locale}/_landing/activity/'
    | '/{-$locale}/_landing/blog/'
    | '/{-$locale}/_landing/settings/'
    | '/{-$locale}/shiponce/categories/'
    | '/{-$locale}/shiponce/posts/'
    | '/{-$locale}/shiponce/roles/'
    | '/{-$locale}/shiponce/users/'
    | '/{-$locale}/_landing/blog/category/$slug'
    | '/{-$locale}/_landing/settings/billing_/cancel'
    | '/{-$locale}/_landing/settings/billing_/retrieve'
    | '/{-$locale}/_landing/settings/invoices_/retrieve'
    | '/{-$locale}/shiponce/categories/$id/edit'
    | '/{-$locale}/shiponce/posts/$id/edit'
    | '/{-$locale}/shiponce/roles/$id/edit'
    | '/{-$locale}/shiponce/roles/$id/edit-permissions'
    | '/{-$locale}/shiponce/users/$id/edit'
    | '/{-$locale}/shiponce/users/$id/edit-roles'
    | '/{-$locale}/shiponce/users/$id/grant-credits'
    | '/{-$locale}/_landing/activity/ai-tasks_/$id/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  Char123indexnowKeyChar125DottxtRoute: typeof Char123indexnowKeyChar125DottxtRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentCallbackRoute: typeof ApiPaymentCallbackRoute
  ApiProxyFileRoute: typeof ApiProxyFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{$indexnowKey}.txt': {
      id: '/{$indexnowKey}.txt'
      path: '/{$indexnowKey}.txt'
      fullPath: '/{$indexnowKey}.txt'
      preLoaderRoute: typeof Char123indexnowKeyChar125DottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/config': {
      id: '/{-$locale}/config'
      path: '/config'
      fullPath: '/{-$locale}/config'
      preLoaderRoute: typeof Char123LocaleChar125ConfigRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_docs': {
      id: '/{-$locale}/_docs'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125DocsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/shiponce': {
      id: '/{-$locale}/shiponce'
      path: '/shiponce'
      fullPath: '/{-$locale}/shiponce'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_oauth': {
      id: '/{-$locale}/_oauth'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125OauthRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_landing': {
      id: '/{-$locale}/_landing'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125LandingRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_auth': {
      id: '/{-$locale}/_auth'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/shiponce/': {
      id: '/{-$locale}/shiponce/'
      path: '/'
      fullPath: '/{-$locale}/shiponce/'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/_landing/': {
      id: '/{-$locale}/_landing/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125LandingIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/shiponce/subscriptions': {
      id: '/{-$locale}/shiponce/subscriptions'
      path: '/subscriptions'
      fullPath: '/{-$locale}/shiponce/subscriptions'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceSubscriptionsRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/permissions': {
      id: '/{-$locale}/shiponce/permissions'
      path: '/permissions'
      fullPath: '/{-$locale}/shiponce/permissions'
      preLoaderRoute: typeof Char123LocaleChar125ShiponcePermissionsRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/payments': {
      id: '/{-$locale}/shiponce/payments'
      path: '/payments'
      fullPath: '/{-$locale}/shiponce/payments'
      preLoaderRoute: typeof Char123LocaleChar125ShiponcePaymentsRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/no-permission': {
      id: '/{-$locale}/shiponce/no-permission'
      path: '/no-permission'
      fullPath: '/{-$locale}/shiponce/no-permission'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceNoPermissionRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/credits': {
      id: '/{-$locale}/shiponce/credits'
      path: '/credits'
      fullPath: '/{-$locale}/shiponce/credits'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceCreditsRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/ai-tasks': {
      id: '/{-$locale}/shiponce/ai-tasks'
      path: '/ai-tasks'
      fullPath: '/{-$locale}/shiponce/ai-tasks'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceAiTasksRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/_oauth/auth-popup': {
      id: '/{-$locale}/_oauth/auth-popup'
      path: '/auth-popup'
      fullPath: '/{-$locale}/auth-popup'
      preLoaderRoute: typeof Char123LocaleChar125OauthAuthPopupRouteImport
      parentRoute: typeof Char123LocaleChar125OauthRouteRoute
    }
    '/{-$locale}/_oauth/auth-callback': {
      id: '/{-$locale}/_oauth/auth-callback'
      path: '/auth-callback'
      fullPath: '/{-$locale}/auth-callback'
      preLoaderRoute: typeof Char123LocaleChar125OauthAuthCallbackRouteImport
      parentRoute: typeof Char123LocaleChar125OauthRouteRoute
    }
    '/{-$locale}/_landing/video-generator': {
      id: '/{-$locale}/_landing/video-generator'
      path: '/video-generator'
      fullPath: '/{-$locale}/video-generator'
      preLoaderRoute: typeof Char123LocaleChar125LandingVideoGeneratorRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/updates': {
      id: '/{-$locale}/_landing/updates'
      path: '/updates'
      fullPath: '/{-$locale}/updates'
      preLoaderRoute: typeof Char123LocaleChar125LandingUpdatesRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/terms-of-service': {
      id: '/{-$locale}/_landing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service'
      preLoaderRoute: typeof Char123LocaleChar125LandingTermsOfServiceRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/showcases': {
      id: '/{-$locale}/_landing/showcases'
      path: '/showcases'
      fullPath: '/{-$locale}/showcases'
      preLoaderRoute: typeof Char123LocaleChar125LandingShowcasesRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/showcase': {
      id: '/{-$locale}/_landing/showcase'
      path: '/showcase'
      fullPath: '/{-$locale}/showcase'
      preLoaderRoute: typeof Char123LocaleChar125LandingShowcaseRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/privacy-policy': {
      id: '/{-$locale}/_landing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125LandingPrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/pricing': {
      id: '/{-$locale}/_landing/pricing'
      path: '/pricing'
      fullPath: '/{-$locale}/pricing'
      preLoaderRoute: typeof Char123LocaleChar125LandingPricingRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/image-generator': {
      id: '/{-$locale}/_landing/image-generator'
      path: '/image-generator'
      fullPath: '/{-$locale}/image-generator'
      preLoaderRoute: typeof Char123LocaleChar125LandingImageGeneratorRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/generate': {
      id: '/{-$locale}/_landing/generate'
      path: '/generate'
      fullPath: '/{-$locale}/generate'
      preLoaderRoute: typeof Char123LocaleChar125LandingGenerateRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/feedback': {
      id: '/{-$locale}/_landing/feedback'
      path: '/feedback'
      fullPath: '/{-$locale}/feedback'
      preLoaderRoute: typeof Char123LocaleChar125LandingFeedbackRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/examples': {
      id: '/{-$locale}/_landing/examples'
      path: '/examples'
      fullPath: '/{-$locale}/examples'
      preLoaderRoute: typeof Char123LocaleChar125LandingExamplesRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/$': {
      id: '/{-$locale}/_landing/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125LandingSplatRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_auth/no-permission': {
      id: '/{-$locale}/_auth/no-permission'
      path: '/no-permission'
      fullPath: '/{-$locale}/no-permission'
      preLoaderRoute: typeof Char123LocaleChar125AuthNoPermissionRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/api/proxy/file': {
      id: '/api/proxy/file'
      path: '/api/proxy/file'
      fullPath: '/api/proxy/file'
      preLoaderRoute: typeof ApiProxyFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/callback': {
      id: '/api/payment/callback'
      path: '/api/payment/callback'
      fullPath: '/api/payment/callback'
      preLoaderRoute: typeof ApiPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_landing/settings': {
      id: '/{-$locale}/_landing/settings'
      path: '/settings'
      fullPath: '/{-$locale}/settings'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsRouteRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/activity': {
      id: '/{-$locale}/_landing/activity'
      path: '/activity'
      fullPath: '/{-$locale}/activity'
      preLoaderRoute: typeof Char123LocaleChar125LandingActivityRouteRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/shiponce/users/': {
      id: '/{-$locale}/shiponce/users/'
      path: '/users'
      fullPath: '/{-$locale}/shiponce/users/'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceUsersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/roles/': {
      id: '/{-$locale}/shiponce/roles/'
      path: '/roles'
      fullPath: '/{-$locale}/shiponce/roles/'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceRolesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/posts/': {
      id: '/{-$locale}/shiponce/posts/'
      path: '/posts'
      fullPath: '/{-$locale}/shiponce/posts/'
      preLoaderRoute: typeof Char123LocaleChar125ShiponcePostsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/categories/': {
      id: '/{-$locale}/shiponce/categories/'
      path: '/categories'
      fullPath: '/{-$locale}/shiponce/categories/'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceCategoriesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/_landing/settings/': {
      id: '/{-$locale}/_landing/settings/'
      path: '/'
      fullPath: '/{-$locale}/settings/'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/blog/': {
      id: '/{-$locale}/_landing/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125LandingBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/activity/': {
      id: '/{-$locale}/_landing/activity/'
      path: '/'
      fullPath: '/{-$locale}/activity/'
      preLoaderRoute: typeof Char123LocaleChar125LandingActivityIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingActivityRouteRoute
    }
    '/{-$locale}/_auth/verify-email/': {
      id: '/{-$locale}/_auth/verify-email/'
      path: '/verify-email'
      fullPath: '/{-$locale}/verify-email/'
      preLoaderRoute: typeof Char123LocaleChar125AuthVerifyEmailIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/_auth/sign-up/': {
      id: '/{-$locale}/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/{-$locale}/sign-up/'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignUpIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/_auth/sign-in/': {
      id: '/{-$locale}/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/{-$locale}/sign-in/'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignInIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/shiponce/settings/$tab': {
      id: '/{-$locale}/shiponce/settings/$tab'
      path: '/settings/$tab'
      fullPath: '/{-$locale}/shiponce/settings/$tab'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceSettingsTabRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/posts/add': {
      id: '/{-$locale}/shiponce/posts/add'
      path: '/posts/add'
      fullPath: '/{-$locale}/shiponce/posts/add'
      preLoaderRoute: typeof Char123LocaleChar125ShiponcePostsAddRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/categories/add': {
      id: '/{-$locale}/shiponce/categories/add'
      path: '/categories/add'
      fullPath: '/{-$locale}/shiponce/categories/add'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceCategoriesAddRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/_landing/video-generator/$slug': {
      id: '/{-$locale}/_landing/video-generator/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/video-generator/$slug'
      preLoaderRoute: typeof Char123LocaleChar125LandingVideoGeneratorSlugRouteImport
      parentRoute: typeof Char123LocaleChar125LandingVideoGeneratorRoute
    }
    '/{-$locale}/_landing/settings/security': {
      id: '/{-$locale}/_landing/settings/security'
      path: '/security'
      fullPath: '/{-$locale}/settings/security'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsSecurityRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/settings/profile': {
      id: '/{-$locale}/_landing/settings/profile'
      path: '/profile'
      fullPath: '/{-$locale}/settings/profile'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsProfileRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/settings/payments': {
      id: '/{-$locale}/_landing/settings/payments'
      path: '/payments'
      fullPath: '/{-$locale}/settings/payments'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsPaymentsRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/settings/credits': {
      id: '/{-$locale}/_landing/settings/credits'
      path: '/credits'
      fullPath: '/{-$locale}/settings/credits'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsCreditsRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/settings/billing': {
      id: '/{-$locale}/_landing/settings/billing'
      path: '/billing'
      fullPath: '/{-$locale}/settings/billing'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsBillingRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/image-generator/$slug': {
      id: '/{-$locale}/_landing/image-generator/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/image-generator/$slug'
      preLoaderRoute: typeof Char123LocaleChar125LandingImageGeneratorSlugRouteImport
      parentRoute: typeof Char123LocaleChar125LandingImageGeneratorRoute
    }
    '/{-$locale}/_landing/blog/$slug': {
      id: '/{-$locale}/_landing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125LandingBlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/ai/music-generator': {
      id: '/{-$locale}/_landing/ai/music-generator'
      path: '/ai/music-generator'
      fullPath: '/{-$locale}/ai/music-generator'
      preLoaderRoute: typeof Char123LocaleChar125LandingAiMusicGeneratorRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/activity/feedbacks': {
      id: '/{-$locale}/_landing/activity/feedbacks'
      path: '/feedbacks'
      fullPath: '/{-$locale}/activity/feedbacks'
      preLoaderRoute: typeof Char123LocaleChar125LandingActivityFeedbacksRouteImport
      parentRoute: typeof Char123LocaleChar125LandingActivityRouteRoute
    }
    '/{-$locale}/_landing/activity/ai-tasks': {
      id: '/{-$locale}/_landing/activity/ai-tasks'
      path: '/ai-tasks'
      fullPath: '/{-$locale}/activity/ai-tasks'
      preLoaderRoute: typeof Char123LocaleChar125LandingActivityAiTasksRouteImport
      parentRoute: typeof Char123LocaleChar125LandingActivityRouteRoute
    }
    '/{-$locale}/_docs/docs/$': {
      id: '/{-$locale}/_docs/docs/$'
      path: '/docs/$'
      fullPath: '/{-$locale}/docs/$'
      preLoaderRoute: typeof Char123LocaleChar125DocsDocsSplatRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRoute
    }
    '/{-$locale}/shiponce/users/$id/grant-credits': {
      id: '/{-$locale}/shiponce/users/$id/grant-credits'
      path: '/users/$id/grant-credits'
      fullPath: '/{-$locale}/shiponce/users/$id/grant-credits'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceUsersIdGrantCreditsRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/users/$id/edit-roles': {
      id: '/{-$locale}/shiponce/users/$id/edit-roles'
      path: '/users/$id/edit-roles'
      fullPath: '/{-$locale}/shiponce/users/$id/edit-roles'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceUsersIdEditRolesRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/users/$id/edit': {
      id: '/{-$locale}/shiponce/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/{-$locale}/shiponce/users/$id/edit'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceUsersIdEditRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/roles/$id/edit-permissions': {
      id: '/{-$locale}/shiponce/roles/$id/edit-permissions'
      path: '/roles/$id/edit-permissions'
      fullPath: '/{-$locale}/shiponce/roles/$id/edit-permissions'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceRolesIdEditPermissionsRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/roles/$id/edit': {
      id: '/{-$locale}/shiponce/roles/$id/edit'
      path: '/roles/$id/edit'
      fullPath: '/{-$locale}/shiponce/roles/$id/edit'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceRolesIdEditRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/posts/$id/edit': {
      id: '/{-$locale}/shiponce/posts/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/{-$locale}/shiponce/posts/$id/edit'
      preLoaderRoute: typeof Char123LocaleChar125ShiponcePostsIdEditRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/shiponce/categories/$id/edit': {
      id: '/{-$locale}/shiponce/categories/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/{-$locale}/shiponce/categories/$id/edit'
      preLoaderRoute: typeof Char123LocaleChar125ShiponceCategoriesIdEditRouteImport
      parentRoute: typeof Char123LocaleChar125ShiponceRouteRoute
    }
    '/{-$locale}/_landing/settings/invoices_/retrieve': {
      id: '/{-$locale}/_landing/settings/invoices_/retrieve'
      path: '/invoices/retrieve'
      fullPath: '/{-$locale}/settings/invoices/retrieve'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsInvoicesRetrieveRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/settings/billing_/retrieve': {
      id: '/{-$locale}/_landing/settings/billing_/retrieve'
      path: '/billing/retrieve'
      fullPath: '/{-$locale}/settings/billing/retrieve'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsBillingRetrieveRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/settings/billing_/cancel': {
      id: '/{-$locale}/_landing/settings/billing_/cancel'
      path: '/billing/cancel'
      fullPath: '/{-$locale}/settings/billing/cancel'
      preLoaderRoute: typeof Char123LocaleChar125LandingSettingsBillingCancelRouteImport
      parentRoute: typeof Char123LocaleChar125LandingSettingsRouteRoute
    }
    '/{-$locale}/_landing/blog/category/$slug': {
      id: '/{-$locale}/_landing/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/{-$locale}/blog/category/$slug'
      preLoaderRoute: typeof Char123LocaleChar125LandingBlogCategorySlugRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/activity/ai-tasks_/$id/refresh': {
      id: '/{-$locale}/_landing/activity/ai-tasks_/$id/refresh'
      path: '/ai-tasks/$id/refresh'
      fullPath: '/{-$locale}/activity/ai-tasks/$id/refresh'
      preLoaderRoute: typeof Char123LocaleChar125LandingActivityAiTasksIdRefreshRouteImport
      parentRoute: typeof Char123LocaleChar125LandingActivityRouteRoute
    }
  }
}

interface Char123LocaleChar125AuthRouteRouteChildren {
  Char123LocaleChar125AuthNoPermissionRoute: typeof Char123LocaleChar125AuthNoPermissionRoute
  Char123LocaleChar125AuthSignInIndexRoute: typeof Char123LocaleChar125AuthSignInIndexRoute
  Char123LocaleChar125AuthSignUpIndexRoute: typeof Char123LocaleChar125AuthSignUpIndexRoute
  Char123LocaleChar125AuthVerifyEmailIndexRoute: typeof Char123LocaleChar125AuthVerifyEmailIndexRoute
}

const Char123LocaleChar125AuthRouteRouteChildren: Char123LocaleChar125AuthRouteRouteChildren =
  {
    Char123LocaleChar125AuthNoPermissionRoute:
      Char123LocaleChar125AuthNoPermissionRoute,
    Char123LocaleChar125AuthSignInIndexRoute:
      Char123LocaleChar125AuthSignInIndexRoute,
    Char123LocaleChar125AuthSignUpIndexRoute:
      Char123LocaleChar125AuthSignUpIndexRoute,
    Char123LocaleChar125AuthVerifyEmailIndexRoute:
      Char123LocaleChar125AuthVerifyEmailIndexRoute,
  }

const Char123LocaleChar125AuthRouteRouteWithChildren =
  Char123LocaleChar125AuthRouteRoute._addFileChildren(
    Char123LocaleChar125AuthRouteRouteChildren,
  )

interface Char123LocaleChar125LandingActivityRouteRouteChildren {
  Char123LocaleChar125LandingActivityAiTasksRoute: typeof Char123LocaleChar125LandingActivityAiTasksRoute
  Char123LocaleChar125LandingActivityFeedbacksRoute: typeof Char123LocaleChar125LandingActivityFeedbacksRoute
  Char123LocaleChar125LandingActivityIndexRoute: typeof Char123LocaleChar125LandingActivityIndexRoute
  Char123LocaleChar125LandingActivityAiTasksIdRefreshRoute: typeof Char123LocaleChar125LandingActivityAiTasksIdRefreshRoute
}

const Char123LocaleChar125LandingActivityRouteRouteChildren: Char123LocaleChar125LandingActivityRouteRouteChildren =
  {
    Char123LocaleChar125LandingActivityAiTasksRoute:
      Char123LocaleChar125LandingActivityAiTasksRoute,
    Char123LocaleChar125LandingActivityFeedbacksRoute:
      Char123LocaleChar125LandingActivityFeedbacksRoute,
    Char123LocaleChar125LandingActivityIndexRoute:
      Char123LocaleChar125LandingActivityIndexRoute,
    Char123LocaleChar125LandingActivityAiTasksIdRefreshRoute:
      Char123LocaleChar125LandingActivityAiTasksIdRefreshRoute,
  }

const Char123LocaleChar125LandingActivityRouteRouteWithChildren =
  Char123LocaleChar125LandingActivityRouteRoute._addFileChildren(
    Char123LocaleChar125LandingActivityRouteRouteChildren,
  )

interface Char123LocaleChar125LandingSettingsRouteRouteChildren {
  Char123LocaleChar125LandingSettingsBillingRoute: typeof Char123LocaleChar125LandingSettingsBillingRoute
  Char123LocaleChar125LandingSettingsCreditsRoute: typeof Char123LocaleChar125LandingSettingsCreditsRoute
  Char123LocaleChar125LandingSettingsPaymentsRoute: typeof Char123LocaleChar125LandingSettingsPaymentsRoute
  Char123LocaleChar125LandingSettingsProfileRoute: typeof Char123LocaleChar125LandingSettingsProfileRoute
  Char123LocaleChar125LandingSettingsSecurityRoute: typeof Char123LocaleChar125LandingSettingsSecurityRoute
  Char123LocaleChar125LandingSettingsIndexRoute: typeof Char123LocaleChar125LandingSettingsIndexRoute
  Char123LocaleChar125LandingSettingsBillingCancelRoute: typeof Char123LocaleChar125LandingSettingsBillingCancelRoute
  Char123LocaleChar125LandingSettingsBillingRetrieveRoute: typeof Char123LocaleChar125LandingSettingsBillingRetrieveRoute
  Char123LocaleChar125LandingSettingsInvoicesRetrieveRoute: typeof Char123LocaleChar125LandingSettingsInvoicesRetrieveRoute
}

const Char123LocaleChar125LandingSettingsRouteRouteChildren: Char123LocaleChar125LandingSettingsRouteRouteChildren =
  {
    Char123LocaleChar125LandingSettingsBillingRoute:
      Char123LocaleChar125LandingSettingsBillingRoute,
    Char123LocaleChar125LandingSettingsCreditsRoute:
      Char123LocaleChar125LandingSettingsCreditsRoute,
    Char123LocaleChar125LandingSettingsPaymentsRoute:
      Char123LocaleChar125LandingSettingsPaymentsRoute,
    Char123LocaleChar125LandingSettingsProfileRoute:
      Char123LocaleChar125LandingSettingsProfileRoute,
    Char123LocaleChar125LandingSettingsSecurityRoute:
      Char123LocaleChar125LandingSettingsSecurityRoute,
    Char123LocaleChar125LandingSettingsIndexRoute:
      Char123LocaleChar125LandingSettingsIndexRoute,
    Char123LocaleChar125LandingSettingsBillingCancelRoute:
      Char123LocaleChar125LandingSettingsBillingCancelRoute,
    Char123LocaleChar125LandingSettingsBillingRetrieveRoute:
      Char123LocaleChar125LandingSettingsBillingRetrieveRoute,
    Char123LocaleChar125LandingSettingsInvoicesRetrieveRoute:
      Char123LocaleChar125LandingSettingsInvoicesRetrieveRoute,
  }

const Char123LocaleChar125LandingSettingsRouteRouteWithChildren =
  Char123LocaleChar125LandingSettingsRouteRoute._addFileChildren(
    Char123LocaleChar125LandingSettingsRouteRouteChildren,
  )

interface Char123LocaleChar125LandingImageGeneratorRouteChildren {
  Char123LocaleChar125LandingImageGeneratorSlugRoute: typeof Char123LocaleChar125LandingImageGeneratorSlugRoute
}

const Char123LocaleChar125LandingImageGeneratorRouteChildren: Char123LocaleChar125LandingImageGeneratorRouteChildren =
  {
    Char123LocaleChar125LandingImageGeneratorSlugRoute:
      Char123LocaleChar125LandingImageGeneratorSlugRoute,
  }

const Char123LocaleChar125LandingImageGeneratorRouteWithChildren =
  Char123LocaleChar125LandingImageGeneratorRoute._addFileChildren(
    Char123LocaleChar125LandingImageGeneratorRouteChildren,
  )

interface Char123LocaleChar125LandingVideoGeneratorRouteChildren {
  Char123LocaleChar125LandingVideoGeneratorSlugRoute: typeof Char123LocaleChar125LandingVideoGeneratorSlugRoute
}

const Char123LocaleChar125LandingVideoGeneratorRouteChildren: Char123LocaleChar125LandingVideoGeneratorRouteChildren =
  {
    Char123LocaleChar125LandingVideoGeneratorSlugRoute:
      Char123LocaleChar125LandingVideoGeneratorSlugRoute,
  }

const Char123LocaleChar125LandingVideoGeneratorRouteWithChildren =
  Char123LocaleChar125LandingVideoGeneratorRoute._addFileChildren(
    Char123LocaleChar125LandingVideoGeneratorRouteChildren,
  )

interface Char123LocaleChar125LandingRouteRouteChildren {
  Char123LocaleChar125LandingActivityRouteRoute: typeof Char123LocaleChar125LandingActivityRouteRouteWithChildren
  Char123LocaleChar125LandingSettingsRouteRoute: typeof Char123LocaleChar125LandingSettingsRouteRouteWithChildren
  Char123LocaleChar125LandingSplatRoute: typeof Char123LocaleChar125LandingSplatRoute
  Char123LocaleChar125LandingExamplesRoute: typeof Char123LocaleChar125LandingExamplesRoute
  Char123LocaleChar125LandingFeedbackRoute: typeof Char123LocaleChar125LandingFeedbackRoute
  Char123LocaleChar125LandingGenerateRoute: typeof Char123LocaleChar125LandingGenerateRoute
  Char123LocaleChar125LandingImageGeneratorRoute: typeof Char123LocaleChar125LandingImageGeneratorRouteWithChildren
  Char123LocaleChar125LandingPricingRoute: typeof Char123LocaleChar125LandingPricingRoute
  Char123LocaleChar125LandingPrivacyPolicyRoute: typeof Char123LocaleChar125LandingPrivacyPolicyRoute
  Char123LocaleChar125LandingShowcaseRoute: typeof Char123LocaleChar125LandingShowcaseRoute
  Char123LocaleChar125LandingShowcasesRoute: typeof Char123LocaleChar125LandingShowcasesRoute
  Char123LocaleChar125LandingTermsOfServiceRoute: typeof Char123LocaleChar125LandingTermsOfServiceRoute
  Char123LocaleChar125LandingUpdatesRoute: typeof Char123LocaleChar125LandingUpdatesRoute
  Char123LocaleChar125LandingVideoGeneratorRoute: typeof Char123LocaleChar125LandingVideoGeneratorRouteWithChildren
  Char123LocaleChar125LandingIndexRoute: typeof Char123LocaleChar125LandingIndexRoute
  Char123LocaleChar125LandingAiMusicGeneratorRoute: typeof Char123LocaleChar125LandingAiMusicGeneratorRoute
  Char123LocaleChar125LandingBlogSlugRoute: typeof Char123LocaleChar125LandingBlogSlugRoute
  Char123LocaleChar125LandingBlogIndexRoute: typeof Char123LocaleChar125LandingBlogIndexRoute
  Char123LocaleChar125LandingBlogCategorySlugRoute: typeof Char123LocaleChar125LandingBlogCategorySlugRoute
}

const Char123LocaleChar125LandingRouteRouteChildren: Char123LocaleChar125LandingRouteRouteChildren =
  {
    Char123LocaleChar125LandingActivityRouteRoute:
      Char123LocaleChar125LandingActivityRouteRouteWithChildren,
    Char123LocaleChar125LandingSettingsRouteRoute:
      Char123LocaleChar125LandingSettingsRouteRouteWithChildren,
    Char123LocaleChar125LandingSplatRoute:
      Char123LocaleChar125LandingSplatRoute,
    Char123LocaleChar125LandingExamplesRoute:
      Char123LocaleChar125LandingExamplesRoute,
    Char123LocaleChar125LandingFeedbackRoute:
      Char123LocaleChar125LandingFeedbackRoute,
    Char123LocaleChar125LandingGenerateRoute:
      Char123LocaleChar125LandingGenerateRoute,
    Char123LocaleChar125LandingImageGeneratorRoute:
      Char123LocaleChar125LandingImageGeneratorRouteWithChildren,
    Char123LocaleChar125LandingPricingRoute:
      Char123LocaleChar125LandingPricingRoute,
    Char123LocaleChar125LandingPrivacyPolicyRoute:
      Char123LocaleChar125LandingPrivacyPolicyRoute,
    Char123LocaleChar125LandingShowcaseRoute:
      Char123LocaleChar125LandingShowcaseRoute,
    Char123LocaleChar125LandingShowcasesRoute:
      Char123LocaleChar125LandingShowcasesRoute,
    Char123LocaleChar125LandingTermsOfServiceRoute:
      Char123LocaleChar125LandingTermsOfServiceRoute,
    Char123LocaleChar125LandingUpdatesRoute:
      Char123LocaleChar125LandingUpdatesRoute,
    Char123LocaleChar125LandingVideoGeneratorRoute:
      Char123LocaleChar125LandingVideoGeneratorRouteWithChildren,
    Char123LocaleChar125LandingIndexRoute:
      Char123LocaleChar125LandingIndexRoute,
    Char123LocaleChar125LandingAiMusicGeneratorRoute:
      Char123LocaleChar125LandingAiMusicGeneratorRoute,
    Char123LocaleChar125LandingBlogSlugRoute:
      Char123LocaleChar125LandingBlogSlugRoute,
    Char123LocaleChar125LandingBlogIndexRoute:
      Char123LocaleChar125LandingBlogIndexRoute,
    Char123LocaleChar125LandingBlogCategorySlugRoute:
      Char123LocaleChar125LandingBlogCategorySlugRoute,
  }

const Char123LocaleChar125LandingRouteRouteWithChildren =
  Char123LocaleChar125LandingRouteRoute._addFileChildren(
    Char123LocaleChar125LandingRouteRouteChildren,
  )

interface Char123LocaleChar125OauthRouteRouteChildren {
  Char123LocaleChar125OauthAuthCallbackRoute: typeof Char123LocaleChar125OauthAuthCallbackRoute
  Char123LocaleChar125OauthAuthPopupRoute: typeof Char123LocaleChar125OauthAuthPopupRoute
}

const Char123LocaleChar125OauthRouteRouteChildren: Char123LocaleChar125OauthRouteRouteChildren =
  {
    Char123LocaleChar125OauthAuthCallbackRoute:
      Char123LocaleChar125OauthAuthCallbackRoute,
    Char123LocaleChar125OauthAuthPopupRoute:
      Char123LocaleChar125OauthAuthPopupRoute,
  }

const Char123LocaleChar125OauthRouteRouteWithChildren =
  Char123LocaleChar125OauthRouteRoute._addFileChildren(
    Char123LocaleChar125OauthRouteRouteChildren,
  )

interface Char123LocaleChar125ShiponceRouteRouteChildren {
  Char123LocaleChar125ShiponceAiTasksRoute: typeof Char123LocaleChar125ShiponceAiTasksRoute
  Char123LocaleChar125ShiponceCreditsRoute: typeof Char123LocaleChar125ShiponceCreditsRoute
  Char123LocaleChar125ShiponceNoPermissionRoute: typeof Char123LocaleChar125ShiponceNoPermissionRoute
  Char123LocaleChar125ShiponcePaymentsRoute: typeof Char123LocaleChar125ShiponcePaymentsRoute
  Char123LocaleChar125ShiponcePermissionsRoute: typeof Char123LocaleChar125ShiponcePermissionsRoute
  Char123LocaleChar125ShiponceSubscriptionsRoute: typeof Char123LocaleChar125ShiponceSubscriptionsRoute
  Char123LocaleChar125ShiponceIndexRoute: typeof Char123LocaleChar125ShiponceIndexRoute
  Char123LocaleChar125ShiponceCategoriesAddRoute: typeof Char123LocaleChar125ShiponceCategoriesAddRoute
  Char123LocaleChar125ShiponcePostsAddRoute: typeof Char123LocaleChar125ShiponcePostsAddRoute
  Char123LocaleChar125ShiponceSettingsTabRoute: typeof Char123LocaleChar125ShiponceSettingsTabRoute
  Char123LocaleChar125ShiponceCategoriesIndexRoute: typeof Char123LocaleChar125ShiponceCategoriesIndexRoute
  Char123LocaleChar125ShiponcePostsIndexRoute: typeof Char123LocaleChar125ShiponcePostsIndexRoute
  Char123LocaleChar125ShiponceRolesIndexRoute: typeof Char123LocaleChar125ShiponceRolesIndexRoute
  Char123LocaleChar125ShiponceUsersIndexRoute: typeof Char123LocaleChar125ShiponceUsersIndexRoute
  Char123LocaleChar125ShiponceCategoriesIdEditRoute: typeof Char123LocaleChar125ShiponceCategoriesIdEditRoute
  Char123LocaleChar125ShiponcePostsIdEditRoute: typeof Char123LocaleChar125ShiponcePostsIdEditRoute
  Char123LocaleChar125ShiponceRolesIdEditRoute: typeof Char123LocaleChar125ShiponceRolesIdEditRoute
  Char123LocaleChar125ShiponceRolesIdEditPermissionsRoute: typeof Char123LocaleChar125ShiponceRolesIdEditPermissionsRoute
  Char123LocaleChar125ShiponceUsersIdEditRoute: typeof Char123LocaleChar125ShiponceUsersIdEditRoute
  Char123LocaleChar125ShiponceUsersIdEditRolesRoute: typeof Char123LocaleChar125ShiponceUsersIdEditRolesRoute
  Char123LocaleChar125ShiponceUsersIdGrantCreditsRoute: typeof Char123LocaleChar125ShiponceUsersIdGrantCreditsRoute
}

const Char123LocaleChar125ShiponceRouteRouteChildren: Char123LocaleChar125ShiponceRouteRouteChildren =
  {
    Char123LocaleChar125ShiponceAiTasksRoute:
      Char123LocaleChar125ShiponceAiTasksRoute,
    Char123LocaleChar125ShiponceCreditsRoute:
      Char123LocaleChar125ShiponceCreditsRoute,
    Char123LocaleChar125ShiponceNoPermissionRoute:
      Char123LocaleChar125ShiponceNoPermissionRoute,
    Char123LocaleChar125ShiponcePaymentsRoute:
      Char123LocaleChar125ShiponcePaymentsRoute,
    Char123LocaleChar125ShiponcePermissionsRoute:
      Char123LocaleChar125ShiponcePermissionsRoute,
    Char123LocaleChar125ShiponceSubscriptionsRoute:
      Char123LocaleChar125ShiponceSubscriptionsRoute,
    Char123LocaleChar125ShiponceIndexRoute:
      Char123LocaleChar125ShiponceIndexRoute,
    Char123LocaleChar125ShiponceCategoriesAddRoute:
      Char123LocaleChar125ShiponceCategoriesAddRoute,
    Char123LocaleChar125ShiponcePostsAddRoute:
      Char123LocaleChar125ShiponcePostsAddRoute,
    Char123LocaleChar125ShiponceSettingsTabRoute:
      Char123LocaleChar125ShiponceSettingsTabRoute,
    Char123LocaleChar125ShiponceCategoriesIndexRoute:
      Char123LocaleChar125ShiponceCategoriesIndexRoute,
    Char123LocaleChar125ShiponcePostsIndexRoute:
      Char123LocaleChar125ShiponcePostsIndexRoute,
    Char123LocaleChar125ShiponceRolesIndexRoute:
      Char123LocaleChar125ShiponceRolesIndexRoute,
    Char123LocaleChar125ShiponceUsersIndexRoute:
      Char123LocaleChar125ShiponceUsersIndexRoute,
    Char123LocaleChar125ShiponceCategoriesIdEditRoute:
      Char123LocaleChar125ShiponceCategoriesIdEditRoute,
    Char123LocaleChar125ShiponcePostsIdEditRoute:
      Char123LocaleChar125ShiponcePostsIdEditRoute,
    Char123LocaleChar125ShiponceRolesIdEditRoute:
      Char123LocaleChar125ShiponceRolesIdEditRoute,
    Char123LocaleChar125ShiponceRolesIdEditPermissionsRoute:
      Char123LocaleChar125ShiponceRolesIdEditPermissionsRoute,
    Char123LocaleChar125ShiponceUsersIdEditRoute:
      Char123LocaleChar125ShiponceUsersIdEditRoute,
    Char123LocaleChar125ShiponceUsersIdEditRolesRoute:
      Char123LocaleChar125ShiponceUsersIdEditRolesRoute,
    Char123LocaleChar125ShiponceUsersIdGrantCreditsRoute:
      Char123LocaleChar125ShiponceUsersIdGrantCreditsRoute,
  }

const Char123LocaleChar125ShiponceRouteRouteWithChildren =
  Char123LocaleChar125ShiponceRouteRoute._addFileChildren(
    Char123LocaleChar125ShiponceRouteRouteChildren,
  )

interface Char123LocaleChar125DocsRouteChildren {
  Char123LocaleChar125DocsDocsSplatRoute: typeof Char123LocaleChar125DocsDocsSplatRoute
}

const Char123LocaleChar125DocsRouteChildren: Char123LocaleChar125DocsRouteChildren =
  {
    Char123LocaleChar125DocsDocsSplatRoute:
      Char123LocaleChar125DocsDocsSplatRoute,
  }

const Char123LocaleChar125DocsRouteWithChildren =
  Char123LocaleChar125DocsRoute._addFileChildren(
    Char123LocaleChar125DocsRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AuthRouteRoute: typeof Char123LocaleChar125AuthRouteRouteWithChildren
  Char123LocaleChar125LandingRouteRoute: typeof Char123LocaleChar125LandingRouteRouteWithChildren
  Char123LocaleChar125OauthRouteRoute: typeof Char123LocaleChar125OauthRouteRouteWithChildren
  Char123LocaleChar125ShiponceRouteRoute: typeof Char123LocaleChar125ShiponceRouteRouteWithChildren
  Char123LocaleChar125DocsRoute: typeof Char123LocaleChar125DocsRouteWithChildren
  Char123LocaleChar125ConfigRoute: typeof Char123LocaleChar125ConfigRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AuthRouteRoute:
      Char123LocaleChar125AuthRouteRouteWithChildren,
    Char123LocaleChar125LandingRouteRoute:
      Char123LocaleChar125LandingRouteRouteWithChildren,
    Char123LocaleChar125OauthRouteRoute:
      Char123LocaleChar125OauthRouteRouteWithChildren,
    Char123LocaleChar125ShiponceRouteRoute:
      Char123LocaleChar125ShiponceRouteRouteWithChildren,
    Char123LocaleChar125DocsRoute: Char123LocaleChar125DocsRouteWithChildren,
    Char123LocaleChar125ConfigRoute: Char123LocaleChar125ConfigRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  Char123indexnowKeyChar125DottxtRoute: Char123indexnowKeyChar125DottxtRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentCallbackRoute: ApiPaymentCallbackRoute,
  ApiProxyFileRoute: ApiProxyFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
